# Generated by Django 4.0.8 on 2023-01-05 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tickets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('B', 'Backend'), ('F', 'Frontend'), ('I', 'Ios'), ('A', 'Android')], default=None, max_length=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('desc', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=50)),
                ('priority', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='L', max_length=1)),
                ('status', models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], default='O', max_length=1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('assignee_user_id', models.OneToOneField(on_delete=models.SET(tickets.models.get_sentinel_user), related_name='issue_assignee', to=settings.AUTH_USER_MODEL)),
                ('author_user_id', models.OneToOneField(on_delete=models.SET(tickets.models.get_sentinel_user), related_name='issue_author', to=settings.AUTH_USER_MODEL)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.project')),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('A', 'Author'), ('C', 'Contributor')], default='A', max_length=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
