# Generated by Django 4.0.8 on 2023-01-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_assignee_user_id_issue_assignee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('R', 'ReadOnly'), ('W', 'Edit')], default='R', max_length=1),
        ),
    ]
