# Generated by Django 4.0.8 on 2023-01-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_project_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(choices=[('A', 'Author'), ('C', 'Contributor')], default='C', max_length=1),
        ),
    ]
