# Generated by Django 4.0.8 on 2023-01-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_contributor_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(choices=[('M', 'Manager'), ('C', 'Contributor')], default='C', max_length=1),
        ),
    ]
