# Generated by Django 4.0.8 on 2023-01-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_alter_contributor_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('R', 'ReadOnly'), ('W', 'Edit')], default='W', max_length=1),
        ),
    ]
